# Generated by Django 6.0.6 on 2026-07-01 17:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staff_salarypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_bus_code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('vehicle_no', models.CharField(blank=True, max_length=60)),
                ('driver_name', models.CharField(blank=True, max_length=80)),
                ('helpline', models.CharField(blank=True, max_length=50)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'vehicle_no'],
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_route_code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('monthly_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_sr_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('legacy_route_name', models.CharField(blank=True, max_length=100)),
                ('legacy_bus_label', models.CharField(blank=True, max_length=60)),
                ('stop_name', models.CharField(blank=True, max_length=100)),
                ('applied_on', models.DateField(blank=True, null=True)),
                ('charge_month', models.CharField(blank=True, max_length=30)),
                ('due_month', models.CharField(blank=True, max_length=30)),
                ('is_transport_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='core.student')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='core.transportbus')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='core.transportroute')),
            ],
            options={
                'ordering': ['student__current_class__display_order', 'student__current_section__name', 'student__full_name'],
            },
        ),
    ]
