# Generated by Django 6.0.6 on 2026-07-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_module_access_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='udise_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='pen_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='book_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='fee_concession_nature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='ncc_scout',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='school_category',
            field=models.CharField(default='Independent', max_length=50),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='sr_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='struck_off_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='subjects_offered',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='whether_failed',
            field=models.BooleanField(default=False),
        ),
    ]
