# Generated by Django 6.0.6 on 2026-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feereceipt_edit_count_feereceipt_edit_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='class_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='father_name_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='section_snapshot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='student_name_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
