# Generated by Django 6.0.6 on 2026-07-05 18:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_feereceipt_class_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('group_type', models.CharField(choices=[('asset', 'Asset'), ('expense', 'Expense'), ('income', 'Income'), ('liability', 'Liability')], default='expense', max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='moduleaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_all_modules', 'SchoolSoft: Access all modules'), ('access_dashboard', 'SchoolSoft: Open dashboard'), ('access_students', 'SchoolSoft: Students and admissions'), ('access_fee_collection', 'SchoolSoft: Fee collection'), ('access_receipts', 'SchoolSoft: Receipt register and receipt PDFs'), ('access_dues', 'SchoolSoft: Dues report'), ('access_collection', 'SchoolSoft: Collection report'), ('access_fee_setup', 'SchoolSoft: Fee setup'), ('access_marks', 'SchoolSoft: Marks and marksheets'), ('access_staff', 'SchoolSoft: Staff and salary'), ('access_transport', 'SchoolSoft: Transport'), ('access_school_profile', 'SchoolSoft: School profile'), ('access_accounts', 'SchoolSoft: Accounts and cash book')], 'verbose_name': 'SchoolSoft module permission', 'verbose_name_plural': 'SchoolSoft module permissions'},
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance when the system starts using this ledger.', max_digits=12)),
                ('opening_balance_date', models.DateField(blank=True, help_text='Date from which the opening balance applies.', null=True)),
                ('is_cash_or_bank', models.BooleanField(default=False, help_text='True for Cash in Hand / Bank accounts (used in Cash Book).')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='core.accountgroup')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('voucher_type', models.CharField(choices=[('CPMT', 'Cash Payment'), ('CREC', 'Cash Receipt'), ('BNK', 'Bank Payment / Receipt'), ('CNTR', 'Contra (Cash ↔ Bank)'), ('OPEN', 'Opening Balance')], default='CPMT', max_length=10)),
                ('voucher_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_to_or_received_from', models.CharField(blank=True, help_text="Person name (e.g. 'Ramesh Driver').", max_length=120)),
                ('narration', models.TextField(blank=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('online', 'Online'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('physical_slip_no', models.CharField(blank=True, help_text='Optional physical voucher pad reference number.', max_length=30)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edit_reason', models.CharField(blank=True, max_length=255)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_vouchers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(help_text='Account credited (money comes FROM this account).', on_delete=django.db.models.deletion.PROTECT, related_name='credit_vouchers', to='core.ledgeraccount')),
                ('debit_account', models.ForeignKey(help_text='Account debited (money goes TO this account).', on_delete=django.db.models.deletion.PROTECT, related_name='debit_vouchers', to='core.ledgeraccount')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_vouchers', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='core.academicsession')),
            ],
            options={
                'ordering': ['-voucher_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('cancelled', 'Cancelled')], max_length=20)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('before_snapshot', models.JSONField(blank=True, null=True)),
                ('after_snapshot', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.voucher')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_counters', to='core.academicsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_date'], name='core_vouche_voucher_adbe50_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_type'], name='core_vouche_voucher_ff5183_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vouchercounter',
            unique_together={('session', 'voucher_type')},
        ),
    ]
