# Generated by Django 6.0.6 on 2026-07-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_salarypayment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='APAAR ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='block',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.CharField(blank=True, help_text='Specific caste/community name, separate from reservation Category.', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='disability',
            field=models.CharField(choices=[('none', 'None'), ('visually_impaired', 'Visually Impaired'), ('hearing_impaired', 'Hearing Impaired'), ('physically_disabled', 'Physically Disabled')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_aadhar_received',
            field=models.BooleanField(default=False, verbose_name='Aadhar Card Received'),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_birth_certificate_received',
            field=models.BooleanField(default=False, verbose_name='Birth Certificate Received'),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_character_certificate_received',
            field=models.BooleanField(default=False, verbose_name='Character Certificate Received'),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_marksheet_received',
            field=models.BooleanField(default=False, verbose_name='Marksheet Received'),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_photo_received',
            field=models.BooleanField(default=False, verbose_name='Passport Photo Received'),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_tc_received',
            field=models.BooleanField(default=False, verbose_name='TC Received'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='father_aadhaar_no',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, help_text='Only if parents are not available.', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_minority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_aadhaar_no',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='post',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_board_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_passing_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_roll_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='village_locality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, help_text='General / OBC / SC / ST only.', max_length=50),
        ),
    ]
