# Generated by Django 6.0.6 on 2026-07-09 17:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_house_disciplinerecord_student_house'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('uniform', 'Uniform'), ('shoes', 'Shoes'), ('book', 'Book'), ('stationery', 'Stationery'), ('other', 'Other')], default='other', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='moduleaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_all_modules', 'SchoolSoft: Access all modules'), ('access_dashboard', 'SchoolSoft: Open dashboard'), ('access_students', 'SchoolSoft: Students and admissions'), ('access_fee_collection', 'SchoolSoft: Fee collection'), ('access_receipts', 'SchoolSoft: Receipt register and receipt PDFs'), ('access_dues', 'SchoolSoft: Dues report'), ('access_collection', 'SchoolSoft: Collection report'), ('access_fee_setup', 'SchoolSoft: Fee setup'), ('access_marks', 'SchoolSoft: Marks and marksheets'), ('access_staff', 'SchoolSoft: Staff and salary'), ('access_transport', 'SchoolSoft: Transport'), ('access_school_profile', 'SchoolSoft: School profile'), ('access_accounts', 'SchoolSoft: Accounts and cash book'), ('access_inventory', 'SchoolSoft: Inventory (uniform/books)')], 'verbose_name': 'SchoolSoft module permission', 'verbose_name_plural': 'SchoolSoft module permissions'},
        ),
        migrations.CreateModel(
            name='InventoryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('amount_charged', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issues_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_issues', to='core.student')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='core.inventoryitem')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
    ]
