# Generated by Django 6.0.6 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_transfercertificate_withdrawal_file_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='previous_due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='carried_forward',
            field=models.BooleanField(default=False, help_text="True if this receipt's outstanding due was rolled into a later receipt as Previous Due - excluded from Due Report totals to avoid double-counting."),
        ),
    ]
