# Generated by Django 6.0.6 on 2026-07-21 11:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_feereceipt_previous_due_carry_forward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('as_of_date', models.DateField()),
                ('source_reference', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['session__name', 'student__full_name'],
            },
        ),
        migrations.AddField(
            model_name='feehead',
            name='applies_to',
            field=models.CharField(choices=[('both', 'New and old'), ('new', 'New only'), ('old', 'Old only')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='feehead',
            name='new_student_charge_months',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feehead',
            name='new_student_charge_rule',
            field=models.CharField(choices=[('monthly', 'Every academic month'), ('admission_month', 'Admission month'), ('fixed_months', 'Configured months'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='feehead',
            name='old_student_charge_months',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feehead',
            name='old_student_charge_rule',
            field=models.CharField(choices=[('monthly', 'Every academic month'), ('admission_month', 'Admission month'), ('fixed_months', 'Configured months'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='source',
            field=models.CharField(choices=[('existing', 'Pre-Phase-B existing row'), ('legacy', 'Legacy import'), ('final_sheet', 'Verified FINAL workbook'), ('manual', 'Manual'), ('bootstrap', 'Bootstrap')], default='existing', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='source_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='billing_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='end_month',
            field=models.CharField(blank=True, choices=[('APR', 'APR'), ('MAY', 'MAY'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AUG', 'AUG'), ('SEP', 'SEP'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC'), ('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR')], max_length=3),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_transport_assignments', to='core.academicsession'),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='start_month',
            field=models.CharField(blank=True, choices=[('APR', 'APR'), ('MAY', 'MAY'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AUG', 'AUG'), ('SEP', 'SEP'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC'), ('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR')], max_length=3),
        ),
        migrations.AlterField(
            model_name='feehead',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One time'), ('monthly', 'Monthly'), ('installment', 'Installment'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('optional', 'Optional')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='carried_forward',
            field=models.BooleanField(default=False, help_text='DEPRECATED for the new fee engine; retained temporarily for the legacy receipt-based Due Report.'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='previous_due_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='DEPRECATED for the new fee engine; retained temporarily for the legacy receipt workflow. New-engine opening balances use StudentOpeningBalance.', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='fee_structure_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studenttransport',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_amount__isnull', True), ('monthly_amount__gte', 0), _connector='OR'), name='student_transport_monthly_amount_nonnegative'),
        ),
        migrations.AddField(
            model_name='studentopeningbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_opening_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentopeningbalance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_opening_balances', to='core.academicsession'),
        ),
        migrations.AddField(
            model_name='studentopeningbalance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='core.student'),
        ),
        migrations.AddConstraint(
            model_name='studentopeningbalance',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_opening_balance_per_session'),
        ),
        migrations.AddConstraint(
            model_name='studentopeningbalance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='student_opening_balance_nonnegative'),
        ),
    ]
