# Generated by Django 6.0.6 on 2026-08-04 16:42

from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def backfill_amount_paid(apps, schema_editor):
    """Existing salary entries used basic_pay as the actual cash given.
    Backfill amount_paid = net_pay (basic+da+allowances - deductions - advance_recovery).
    Only update rows still at default 0.00 so re-runs are safe."""
    SalaryPayment = apps.get_model("core", "SalaryPayment")
    SalaryPayment.objects.filter(amount_paid=Decimal("0.00")).update(
        amount_paid=(
            F("basic_pay") + F("da") + F("other_allowances")
            - F("pf_deduction") - F("esi_deduction")
            - F("other_deduction") - F("advance_recovery")
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_person_ledgeraccount_person'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salarypayment',
            name='unique_active_salary',
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount handed to staff in this payment slip.', max_digits=10),
        ),
        migrations.RunPython(backfill_amount_paid, migrations.RunPython.noop),
    ]
