# Generated by Django 6.0.6 on 2026-08-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_student_hindi_names_exam_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject_1_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='1st Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_2_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='2nd Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_3_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='3rd Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_4_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='4th Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_5_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='5th Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_6_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='6th Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_7_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='7th Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_group',
            field=models.CharField(blank=True, choices=[('HS', 'High School (IX/X)'), ('A', 'Arts / Humanities'), ('B', 'Science'), ('C', 'Commerce')], help_text='Board subject group for Class IX-XII admission forms.', max_length=10, verbose_name='Subject Group'),
        ),
    ]
