# Generated by Django 6.0.6 on 2026-08-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_student_subject_1_code_student_subject_2_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address_street_area',
            field=models.CharField(blank=True, max_length=150, verbose_name='Street / Mohalla / Area'),
        ),
        migrations.AddField(
            model_name='student',
            name='board_candidate_type_1_code',
            field=models.CharField(blank=True, choices=[('1', '1 - Regular'), ('2', '2 - Reappear / Re-admission'), ('3', '3 - Other Recognised School')], default='1', max_length=1, verbose_name='Board Candidate Type 1'),
        ),
        migrations.AddField(
            model_name='student',
            name='board_candidate_type_2_code',
            field=models.CharField(blank=True, choices=[('0', '0 - None'), ('1', '1 - Blindness'), ('2', '2 - Hearing Impairment'), ('3', '3 - Multiple Disabilities incl. Deaf-blindness'), ('4', '4 - Low Vision'), ('5', '5 - Leprosy Cured'), ('6', '6 - Locomotor Disability'), ('7', '7 - Dwarfism'), ('8', '8 - Intellectual Disability'), ('9', '9 - Mental Illness'), ('10', '10 - Autism Spectrum Disorder'), ('11', '11 - Cerebral Palsy'), ('12', '12 - Muscular Dystrophy'), ('13', '13 - Chronic Neurological Conditions'), ('14', '14 - Specific Learning Disabilities'), ('15', '15 - Multiple Sclerosis'), ('16', '16 - Speech and Language Disability'), ('17', '17 - Thalassemia'), ('18', '18 - Hemophilia'), ('19', '19 - Sickle Cell Disease'), ('20', '20 - Acid Attack Victim'), ('21', '21 - Parkinsons Disease')], default='0', max_length=2, verbose_name='Board Candidate Type 2'),
        ),
        migrations.AddField(
            model_name='student',
            name='board_caste_code',
            field=models.CharField(blank=True, choices=[('1', '1 - SC'), ('2', '2 - ST'), ('3', '3 - OBC'), ('4', '4 - General'), ('5', '5 - EWS')], max_length=1, verbose_name='Board Caste Code'),
        ),
        migrations.AddField(
            model_name='student',
            name='board_sr_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Board Sr Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='class8_unique_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Class 8 Unique ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_board_source',
            field=models.CharField(blank=True, choices=[('upboard', 'Class 11 - UP Board'), ('other', 'Class 11 - Other Board')], help_text='Required to choose Class 11 UP Board vs Other Board registration format.', max_length=10, verbose_name='Previous Board Source'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, default='Uttar Pradesh', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_rev_voc_code',
            field=models.CharField(blank=True, help_text='UP Board Class 9 SubjectRevVOCCode column.', max_length=10, verbose_name='Subject RevVOC'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_voc_code',
            field=models.CharField(blank=True, help_text='UP Board SubjectVOCCode column.', max_length=10, verbose_name='Subject VOC'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, help_text='General / OBC / SC / ST / EWS.', max_length=50),
        ),
    ]
