# Generated by Django 6.0.6 on 2026-08-14 17:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_student_address_street_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_package_enabled',
            field=models.BooleanField(default=False, help_text='Use for Section D/Commerce package students or direct X/XII negotiated admission.', verbose_name='Package Fee Applicable'),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_package_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Package Note'),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_package_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Package Total'),
        ),
    ]
