# Generated by Django 6.0.6 on 2026-07-01 12:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-starts_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('legacy_column', models.CharField(blank=True, max_length=80)),
                ('frequency', models.CharField(choices=[('one_time', 'One time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('optional', 'Optional')], default='monthly', max_length=20)),
                ('is_transport', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegacyImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_database', models.CharField(max_length=255)),
                ('source_table', models.CharField(max_length=80)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('records_imported', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.schoolclass')),
            ],
            options={
                'ordering': ['school_class__display_order', 'name'],
                'unique_together': {('school_class', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_sid', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('admission_no', models.CharField(blank=True, max_length=30)),
                ('registration_no', models.CharField(blank=True, max_length=30)),
                ('roll_no', models.PositiveIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=120)),
                ('father_name', models.CharField(blank=True, max_length=120)),
                ('mother_name', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('aadhaar_no', models.CharField(blank=True, max_length=25)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('mobile_primary', models.CharField(blank=True, max_length=50)),
                ('mobile_secondary', models.CharField(blank=True, max_length=50)),
                ('address_permanent', models.TextField(blank=True)),
                ('address_local', models.TextField(blank=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.schoolclass')),
                ('current_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.section')),
            ],
            options={
                'ordering': ['current_class__display_order', 'current_section__name', 'roll_no', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_receipt_no', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('receipt_no', models.CharField(max_length=30, unique=True)),
                ('receipt_date', models.DateField(default=django.utils.timezone.localdate)),
                ('from_month', models.CharField(blank=True, max_length=25)),
                ('to_month', models.CharField(blank=True, max_length=25)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('concession_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_receipts', to='core.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_receipts', to='core.student')),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='core.feehead')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.feereceipt')),
            ],
            options={
                'ordering': ['fee_head__name'],
                'unique_together': {('receipt', 'fee_head')},
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.feehead')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.academicsession')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.schoolclass')),
            ],
            options={
                'ordering': ['session__name', 'school_class__display_order', 'fee_head__name'],
                'unique_together': {('session', 'school_class', 'fee_head')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='core_studen_full_na_d1f1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_no'], name='core_studen_admissi_6442cb_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['legacy_sid'], name='core_studen_legacy__aad329_idx'),
        ),
        migrations.AddIndex(
            model_name='feereceipt',
            index=models.Index(fields=['receipt_date'], name='core_feerec_receipt_ff8b78_idx'),
        ),
        migrations.AddIndex(
            model_name='feereceipt',
            index=models.Index(fields=['legacy_receipt_no'], name='core_feerec_legacy__b31a27_idx'),
        ),
    ]
