# Generated by Django 6.0.6 on 2026-07-01 16:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schoolprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('legacy_code', models.CharField(blank=True, max_length=40)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='core.academicsession')),
            ],
            options={
                'ordering': ['session__name', 'display_order', 'name'],
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExamTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('pass_marks', models.DecimalField(decimal_places=2, default=Decimal('33.00'), max_digits=6)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_tests', to='core.schoolclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.examterm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_tests', to='core.subject')),
            ],
            options={
                'ordering': ['term__display_order', 'school_class__display_order', 'subject__display_order'],
                'unique_together': {('term', 'school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tc_number', models.CharField(max_length=30, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('last_section', models.CharField(blank=True, max_length=10)),
                ('reason_for_leaving', models.CharField(blank=True, max_length=255)),
                ('conduct', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('poor', 'Poor')], default='good', max_length=20)),
                ('general_progress', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('poor', 'Poor')], default='good', max_length=20)),
                ('total_working_days', models.PositiveIntegerField(blank=True, null=True)),
                ('days_present', models.PositiveIntegerField(blank=True, null=True)),
                ('fees_paid_upto', models.CharField(blank=True, max_length=50)),
                ('qualified_for_promotion', models.BooleanField(default=True)),
                ('promoted_to_class', models.CharField(blank=True, max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('last_class_studied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_certificates', to='core.schoolclass')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_certificate', to='core.student')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('remarks', models.CharField(blank=True, max_length=120)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='core.student')),
                ('exam_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.examtest')),
            ],
            options={
                'ordering': ['exam_test__subject__display_order'],
                'unique_together': {('exam_test', 'student')},
            },
        ),
    ]
