# Generated by Django 6.0.6 on 2026-07-01 17:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_examterm_examtest_transfercertificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_emp_code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=80)),
                ('staff_type', models.CharField(choices=[('teaching', 'Teaching'), ('non_teaching', 'Non-teaching'), ('admin', 'Admin'), ('other', 'Other')], default='teaching', max_length=20)),
                ('qualification', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('pf_applicable', models.BooleanField(default=False)),
                ('pf_account_no', models.CharField(blank=True, max_length=40)),
                ('esi_applicable', models.BooleanField(default=False)),
                ('esi_account_no', models.CharField(blank=True, max_length=40)),
                ('basic_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='core_staff_full_na_206bec_idx'), models.Index(fields=['legacy_emp_code'], name='core_staff_legacy__812743_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slip_no', models.CharField(max_length=30, unique=True)),
                ('pay_month', models.DateField(help_text='Use the 1st of the salary month, e.g. 2026-07-01 for July 2026.')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('basic_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('esi_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='core.staff')),
            ],
            options={
                'ordering': ['-pay_month', '-id'],
                'unique_together': {('staff', 'pay_month')},
            },
        ),
    ]
