# Generated by Django 6.0.6 on 2026-07-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transportbus_transportroute_studenttransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransport',
            name='legacy_father_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='legacy_student_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
