# Generated by Django 6.0.6 on 2026-07-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_accounts_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Linked staff member for salary and staff advance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='core.staff'),
        ),
    ]
