# Generated by Django 6.0.6 on 2026-07-06 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_salarypayment_advance_recovery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salarypayment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('staff', 'pay_month'), name='unique_active_salary'),
        ),
    ]
