# Generated by Django 6.0.6 on 2026-07-09 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_student_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color_code', models.CharField(blank=True, help_text="e.g. #DC2626 or 'Red'", max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('late_coming', 'Late Coming'), ('attendance', 'Attendance Issue'), ('misconduct', 'Misconduct'), ('bullying', 'Bullying / Ragging'), ('property_damage', 'Property Damage'), ('academic_dishonesty', 'Academic Dishonesty (Cheating)'), ('uniform_grooming', 'Uniform / Grooming'), ('other', 'Other')], default='other', max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('severe', 'Severe')], default='minor', max_length=10)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_records_reported', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='core.student')),
            ],
            options={
                'ordering': ['-incident_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.house'),
        ),
    ]
