# Generated by Django 6.0.6 on 2026-07-10 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_inventoryitem_alter_moduleaccess_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Usually the father's name - shown as the family label.", max_length=120)),
                ('primary_mobile', models.CharField(blank=True, max_length=20)),
                ('secondary_mobile', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='moduleaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_all_modules', 'SchoolSoft: Access all modules'), ('access_dashboard', 'SchoolSoft: Open dashboard'), ('access_students', 'SchoolSoft: Students and admissions'), ('access_fee_collection', 'SchoolSoft: Fee collection'), ('access_receipts', 'SchoolSoft: Receipt register and receipt PDFs'), ('access_dues', 'SchoolSoft: Dues report'), ('access_collection', 'SchoolSoft: Collection report'), ('access_fee_setup', 'SchoolSoft: Fee setup'), ('access_marks', 'SchoolSoft: Marks and marksheets'), ('access_staff', 'SchoolSoft: Staff and salary'), ('access_transport', 'SchoolSoft: Transport'), ('access_school_profile', 'SchoolSoft: School profile'), ('access_accounts', 'SchoolSoft: Accounts and cash book'), ('access_inventory', 'SchoolSoft: Inventory (uniform/books)'), ('access_family', 'SchoolSoft: Family Ledger (siblings)')], 'verbose_name': 'SchoolSoft module permission', 'verbose_name_plural': 'SchoolSoft module permissions'},
        ),
        migrations.AddField(
            model_name='student',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.family'),
        ),
    ]
