# Generated by Django 6.0.6 on 2026-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_align_tc_book_and_sr_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercertificate',
            name='withdrawal_file_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
