# Generated by Django 6.0.6 on 2026-07-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_create_balance_fee_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('person_type', models.CharField(choices=[('lender', 'Lender'), ('manager', 'Manager'), ('vendor', 'Vendor'), ('other', 'Other')], default='other', max_length=20)),
                ('contact_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Optional link to a Person for consolidating personal accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='core.person'),
        ),
    ]
