# Generated by Django 6.0.6 on 2026-08-12 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_salary_partial_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_type', models.CharField(choices=[('monthly_waiver', 'Monthly Fee Waiver'), ('one_time', 'One-time Concession'), ('full_free', 'Full Free'), ('sibling_discount', 'Sibling Discount')], default='monthly_waiver', max_length=20, verbose_name='Concession Type')),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage'), ('full', '100% Free')], default='fixed', max_length=10, verbose_name='Amount Type')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='For fixed: rupees. For percent: e.g. 50. Leave blank for Full Free.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount / Percentage')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('approved_by_name', models.CharField(max_length=100, verbose_name='Approved By')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='core.academicsession', verbose_name='Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='core.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Concession',
                'verbose_name_plural': 'Student Concessions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'session'), name='unique_active_concession_per_student_session')],
            },
        ),
    ]
