# Generated by Django 6.0.6 on 2026-08-17 12:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_student_fee_package_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, help_text='General / OBC / SC / ST only.', max_length=50),
        ),
        migrations.CreateModel(
            name='FeederSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='School Name')),
                ('code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='School Code')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person / Manager / Principal')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('village_address', models.CharField(blank=True, max_length=200, verbose_name='Village / Town / Location')),
                ('package_rate_per_student', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), help_text='Fixed 2-year package rate per student (e.g. ₹1,500 or ₹1,800).', max_digits=10, verbose_name='Package Rate per Student (₹)')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ledger_account', models.OneToOneField(blank=True, help_text='Linked Sundry Debtors ledger account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_school_profile', to='core.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Attached / Feeder School',
                'verbose_name_plural': 'Attached / Feeder Schools',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='feeder_school',
            field=models.ForeignKey(blank=True, help_text='Feeder school (अटैच्ड विद्यालय) if student belongs to Section B/C.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.feederschool', verbose_name='Attached Feeder School'),
        ),
    ]
