# Generated by Django 6.0.6 on 2026-08-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_student_category_feederschool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('month', models.PositiveSmallIntegerField(help_text='Month number 1 to 12')),
                ('total_working_days', models.PositiveSmallIntegerField(default=24, help_text='Total school working days in this month')),
                ('days_present', models.PositiveSmallIntegerField(default=0, help_text='Number of days the student was present')),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_summaries', to='core.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='core.student')),
            ],
            options={
                'ordering': ['-year', '-month', 'student__current_class__display_order', 'student__roll_no', 'student__full_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'session', 'year', 'month'), name='unique_student_attendance_month_summary'), models.CheckConstraint(condition=models.Q(('days_present__lte', models.F('total_working_days'))), name='attendance_days_present_lte_working_days')],
            },
        ),
    ]
