# Generated by Django 6.0.6 on 2026-08-24 05:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_attendancesummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('waiver_type', models.CharField(choices=[('write_off', 'Write-off / Waiver'), ('section_change', 'Section Change Correction'), ('concession', 'Custom Concession'), ('other', 'Other Adjustment')], default='write_off', max_length=30)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('entered_by', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_fee_waivers', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_waivers', to='core.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_waivers', to='core.student')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='student_fee_waiver_amount_nonnegative')],
            },
        ),
    ]
