# Generated by Django 6.0.6 on 2026-08-25 16:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_studentfeewaiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammark',
            name='practical_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='exammark',
            name='theory_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='examtest',
            name='practical_max_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='examtest',
            name='theory_max_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6),
        ),
    ]
