# Generated by Django 6.0.6 on 2026-09-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_exammark_practical_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='originating_session',
            field=models.ForeignKey(blank=True, help_text='Original academic session for which this arrears payment was incurred.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_fee_receipts', to='core.academicsession'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
