"""
Django settings for schoolsoft project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def local_data_dir():
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return BASE_DIR

# Loads D:\english medium\schoolsoft_web\.env when present. On Render (and other
# hosts) the same variables are set directly in the environment, so this is a
# no-op there - .env is only for local/desktop use and should not be committed.
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=()):
    value = os.environ.get(name)
    if not value:
        return list(default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set SCHOOLSOFT_SECRET_KEY in the environment (or .env) for any real deployment.
SECRET_KEY = os.environ.get(
    "SCHOOLSOFT_SECRET_KEY",
    "django-insecure-=2v@deh(c@+#twq)%gc$^61h%fg^-24p#)bzh86s17mcrp@%ie",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True so local runserver/.exe usage keeps working unchanged.
# Set SCHOOLSOFT_DEBUG=False in the environment for the online deployment.
DEBUG = env_bool("SCHOOLSOFT_DEBUG", default=True)

ALLOWED_HOSTS = env_list(
    "SCHOOLSOFT_ALLOWED_HOSTS",
    default=["127.0.0.1", "localhost", "english-medium.thpsic.com"],
)

# Render sets RENDER_EXTERNAL_HOSTNAME automatically for the service's *.onrender.com URL.
_render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)

CSRF_TRUSTED_ORIGINS = env_list(
    "SCHOOLSOFT_CSRF_TRUSTED_ORIGINS",
    default=["https://english-medium.thpsic.com"],
)
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_render_host}")


# Application definition

INSTALLED_APPS = [
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'schoolsoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'schoolsoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Local desktop/.exe usage keeps using SQLite automatically (no env needed).
# For the online deployment, set DATABASE_URL (Render provides this for its
# managed PostgreSQL, e.g. postgresql://user:pass@host:5432/dbname).

_database_url = os.environ.get("DATABASE_URL")
if _database_url:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(_database_url, conn_max_age=600, ssl_require=not DEBUG)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(os.environ.get("SCHOOLSOFT_SQLITE_PATH", local_data_dir() / "db.sqlite3")),
            # Waitress serves the desktop EXE with multiple threads; without a
            # busy-timeout, concurrent writes intermittently raise
            # "database is locked".
            'OPTIONS': {'timeout': 20},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise serves compressed, cache-busted static files directly from Django,
# so the online deployment does not need a separate Nginx/static host to start.
#
# The Manifest variant requires every referenced static file to already be
# collected (via `collectstatic`) or it raises ValueError on first request -
# fine for production (build step runs collectstatic), but painful for local
# runserver/.exe/test runs where nobody runs collectstatic by hand. So: plain
# storage in DEBUG, manifest+compression only when DEBUG=False.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Request-time errors (500s) are otherwise invisible in the desktop EXE
# (no console). desktop.py sets SCHOOLSOFT_LOG_FILE; when present, log
# django.request errors there. Online (Render) keeps console logging.
_log_file = os.environ.get("SCHOOLSOFT_LOG_FILE")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"},
    },
    "handlers": {
        "errors": (
            {
                "class": "logging.FileHandler",
                "filename": _log_file,
                "encoding": "utf-8",
                "formatter": "verbose",
            }
            if _log_file
            else {"class": "logging.StreamHandler", "formatter": "verbose"}
        ),
    },
    "loggers": {
        "django.request": {"handlers": ["errors"], "level": "ERROR", "propagate": False},
        "django.security": {"handlers": ["errors"], "level": "ERROR", "propagate": False},
    },
}

# Render (and most PaaS hosts) terminate HTTPS at a proxy and forward plain
# HTTP internally, so Django needs this header to know the original request
# was secure - otherwise redirects/CSRF checks misbehave behind the proxy.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = env_bool("SCHOOLSOFT_SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SCHOOLSOFT_SECURE_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SCHOOLSOFT_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
    SECURE_HSTS_PRELOAD = env_bool("SCHOOLSOFT_SECURE_HSTS_PRELOAD", default=False)
